
// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const SETTINGS_SAVED = 'SETTINGS_SAVED';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';

// ADMIN ACTIONS
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'; 
export const SHOW_EMPLOYEE = 'SHOW_EMPLOYEE'; 
export const LIST_EMPLOYEES = 'LIST_EMPLOYEES';
export const OPEN_ADD_EMPLOYEE_DIALOG = 'OPEN_ADD_EMPLOYEE_DIALOG';
export const CLOSE_ADD_EMPLOYEE_DIALOG = 'CLOSE_ADD_EMPLOYEE_DIALOG';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';

// EMPLOYEE ACTION 
export const ATTENDANCES_LIST = 'ATTENDANCES_LIST';
export const START_CLOCK = 'START_CLOCK';
export const STOP_CLOCK = 'STOP_CLOCK';