# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d62f8f21ab58cf9e4d349f78ef4c2ebba8951c3a8c9df890342d3167b5200c42811c65eac89afe044e5b74a96601e6612fb97d0ba1af98db6591d25d6aee18ca

test:
  secret_key_base: e5b8b41abbe7ff80a27189fe1aeffbbdcf605ce4097b6280107691d9016598bd9200a5456c63b7d80047e4d88826ae720820b1c51719add4e8018bb6a9906f31

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
